version: "3.3"

#volumes:

  # Configuration example for External HD #1
  # (credentials stored in .env file)
  #external-hd1:
  #  driver: local
  #  driver_opts:
  #    type: cifs
  #    o: username=${EXTERNAL_HD1_USERNAME},password=${EXTERNAL_HD1_PASSWORD},uid=${USER_PUID},gid=${USER_PGID},iocharset=utf8,file_mode=0777,dir_mode=0777
  #    device: "${EXTERNAL_HD1_PATH}"

services:

  # ==========================================================================
  # Transmission-OpenVPN service
  # => torrent server secured by VPN connection
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    cap_add:
      # Admin credentials for docker container
      - NET_ADMIN
    environment:
      - CREATE_TUN_DEVICE=true
      # OpenVPN settings
      - OPENVPN_PROVIDER=surfshark
      # OPENVPN_CONFIG: comma separated list allowed, with random selection at startup
      - OPENVPN_CONFIG=fr-par_udp
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      # OpenVPN credentials to connect to VPN (credentials stored in .env file)
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # Transmission dirs
      - TRANSMISSION_HOME=/data/transmission-home
      - TRANSMISSION_DOWNLOAD_DIR=/storage/complete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR=/storage/incomplete
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/storage/watch
      # Transmission download / uploads settings
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1000
      # Transmission Web UI: kettu, combustion, transmission-web-control, flood-for-transmission
      - TRANSMISSION_WEB_UI=flood-for-transmission
      # Enable HTTP proxy
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8789
      # Firewall and routes (block non VPN traffic)
      - DROP_DEFAULT_ROUTE=true
      # Firewall not working anymore with docker image v3 / new PIA servers ?
      # - ENABLE_UFW=true
      # - UFW_ALLOW_GW_NET=true
      # - UFW_EXTRA_PORTS=
      # - UFW_DISABLE_IPTABLES_REJECT=false
      # Network settings
      - LOCAL_NETWORK=192.168.0.0/24
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Configuration dir
      - /share/Download/tools/transmission:/data/transmission-home
      # Storage dirs
      - /share/Download/incomplete:/storage/incomplete
      - /share/Download/complete:/storage/complete
      - /share/Download/watch:/storage/watch
    ports:
      # Transmission Web UI port
      - 9091:9091
      # HTTP Proxy port
      - 8789:8789
      # JOAL Web UI Port
      - 9092:9092
    restart: always

  # ==========================================================================
  # JOAL service
  # => Ratio Master clone with web UI to boost torrent seed ratio
  joal:
    image: anthonyraymond/joal:latest
    container_name: joal
    depends_on:
      - transmission-openvpn
    volumes:
      # Configuration dir
      - /share/Download/tools/joal:/data
    # Use network from transmission-openvpn container to ensure traffic goes through VPN tunnel
    network_mode: "service:transmission-openvpn"
    # User from docker host to impersonate in container (configured in .env file)
    user: "${USER_PUID}:${USER_PGID}"
    restart: always
    command: "--joal-conf=/data --spring.main.web-environment=true --server.port=9092 --joal.ui.path.prefix=${JOAL_PATH_PREFIX} --joal.ui.secret-token=${JOAL_SECRET_TOKEN}"

  # ==========================================================================
  # Medusa service
  # => TV shows manager and auto-downloader, connected to torrent server
  medusa:
    image: ghcr.io/linuxserver/medusa:latest
    container_name: medusa
    dns:
      # Public DNS
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Configuration dir
      - /share/Download/tools/medusa:/config
      # Storage dirs
      - /share/Download/complete/medusa:/storage/complete/medusa
      - /share/Multimedia/Series:/storage/Series
      #- external-hd1:/storage/_hd1
    ports:
      # Medusa Web UI port
      - 8081:8081
    restart: always

  # ==========================================================================
  # CouchPotato service
  # => Movies manager and auto-downloader, connected to torrent server
  couchpotato:
    image: ghcr.io/linuxserver/couchpotato:latest
    container_name: couchpotato
    dns:
      # Public DNS
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Configuration dir
      - /share/Download/tools/couchpotato:/config
      # Storage dirs
      - /share/Download/complete/couchpotato:/storage/complete/couchpotato
      - /share/Multimedia/Films:/storage/Films
      #- external-hd1:/storage/_hd1
    ports:
      # CouchPotato Web UI port
      - 5051:5051
    restart: always
  
  # ==========================================================================
  # nginx service
  # => Reverse proxy, used to expose services as HTTPS with SSL certificates and basic authentication
  nginx:
    image: nginx:latest
    container_name: nginx
    dns:
      # Public DNS
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Configuration file
      - /share/Download/tools/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Password file (use 'configurator' docker container to generate)
      - /share/Download/tools/nginx/passwords:/etc/nginx/passwords:ro
      # Logs dir
      - /share/Download/tools/nginx/logs:/var/log/nginx
      # SSL certificates
      - /share/Download/tools/ssl/ahuh.crt:/etc/nginx/certs/ssl.crt:ro
      - /share/Download/tools/ssl/ahuh.key:/etc/nginx/certs/ssl.key:ro
    ports:
      # CouchPotato external port
      - 44451:44451
      # Medusa external port
      - 44481:44481
      # Transmission external port      
      - 44491:44491
    # User from docker host to impersonate in container (configured in .env file)
    user: "${USER_PUID}:${USER_PGID}"
    restart: always

  # ==========================================================================
  # MiniDLNA service
  # => UPnP / DLNA service, used to publish media files on the local network
  minidlna:
    image: vladgh/minidlna:latest
    container_name: minidlna
    network_mode: "host"
    environment:
      # MiniDLNA settings
      - MINIDLNA_FRIENDLY_NAME=ahuh-qnas-mini
      - MINIDLNA_MEDIA_DIR=/storage
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Configuration dir
      - /share/Download/tools/minidlna:/minidlna
      # Storage dirs
      - /share/Download/complete:/storage/complete:ro
      - /share/Perso/Backup:/storage/Backup:ro
      - /share/Perso/Photos:/storage/Photos:ro
      - /share/Perso/Videos:/storage/Videos:ro
      - /share/Multimedia/Films:/storage/Films:ro
      - /share/Multimedia/MP3:/storage/MP3:ro
      - /share/Multimedia/Series:/storage/Series:ro
      - /share/Multimedia/Enfants/Films:/storage/Enfants/Films:ro
      - /share/Multimedia/Enfants/Series:/storage/Enfants/Series:ro
      - /share/Multimedia/Enfants/Videos:/storage/Enfants/Videos:ro
      #- external-hd1:/storage/_hd1:ro
    restart: always

  # ==========================================================================
  # pyphotorg service
  # => Photo organizer and deduplicator, used to manage photos / videos on the NAS
  pyphotorg:
    image: ahuh/pyphotorg:latest
    container_name: pyphotorg
    environment:
      # Operation switches
      - ENABLE_ORGANIZE=true
      - ENABLE_DEDUPLICATE=true
      # Dry-run mode (no modification applied) or real mode
      - DRY_RUN_MODE=false
      # Job scheduler (cron format)
      - "SCHEDULE_CRON=15 2 * * sun"
      # Deduplicator - Dirs and priority orders for duplicate removal (remove duplicates from highest to lowest number)
      - "DEDUP_STORAGE_PATH=/storage/Photos"
      - "DEDUP_BACKUP_PATH=/storage/Backup/pyphotorg"
      - "DEDUP_DIR_ORDER_01=/storage/Photos/Famille"
      - "DEDUP_DIR_ORDER_02=/storage/Photos/Amis"
      - "DEDUP_DIR_ORDER_03=/storage/Photos/Mobile Olivia"
      - "DEDUP_DIR_ORDER_04=/storage/Photos/Mobile Julien"
      - "DEDUP_DIR_PATH_FILTER=/.@__thumb"
      # Organizer - Path couples: sync dirs (source) and storage dirs (target)
      - "ORG_INCOMING_PATH_01=/storage/sync/camera-osiris"
      - "ORG_STORAGE_PATH_01=/storage/Photos/Mobile Julien"
      - "ORG_INCOMING_PATH_02=/storage/sync/camera-olivia"
      - "ORG_STORAGE_PATH_02=/storage/Photos/Mobile Olivia"
      # Organizer parameters
      - ORG_TIMESTAMP_TAGS=FileModifyDate,CreationDate,CreateDate,DateTimeOriginal
      - ORG_STORAGE_PATH_PATTERN=%Y/%Y-%m/%Y%m%d_%H%M%S%%-3c.%%e
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Sync dir
      - /share/homes/ahuh/.Qsync:/storage/sync
      # Storage dir
      - /share/Perso/Photos:/storage/Photos
      # Backup dir
      - /share/Perso/Backup/pyphotorg:/storage/Backup/pyphotorg
    restart: always