version: "3.3"

services:
  
  # ==========================================================================
  # Configurator service for torrent factory
  # => initialize or update config files for other services (MiniDLNA, Medusa, CouchPotato, nginx)
  # => must be executed on-demand before starting other services
  configurator:
    build: ./configurator
    container_name: configurator

    environment:
      # _______________________________________________________________
      # Medusa config
      # • Use HTTP proxy for torrent search (true / false)
      - MEDUSA_USE_HTTP_PROXY=false
      # • Torrent dirs
      - MEDUSA_TORRENT_DOWNLOAD_DIR=/storage/complete/medusa
      - MEDUSA_TORRENT_SEED_DIR=/storage/complete/seed
      # • Storage dirs for TV shows : MEDUSA_TVSHOWS_MAIN_DIR required, add MEDUSA_TVSHOWS_DIR_* vars for additional dirs
      - MEDUSA_TVSHOWS_MAIN_DIR=/storage/Series      
      - MEDUSA_TVSHOWS_DIR_2=/storage/_hd1/Series
      - MEDUSA_TVSHOWS_DIR_3=/storage/_hd1/Enfants/Series
      # _______________________________________________________________
      # CouchPotato config
      # • Use HTTP proxy for torrent search (true / false)
      - COUCHPOTATO_USE_HTTP_PROXY=false
      # • Torrent dirs
      - COUCHPOTATO_TORRENT_DOWNLOAD_DIR=/storage/complete/couchpotato
      # • Storage dirs for movies : COUCHPOTATO_MOVIES_MAIN_DIR required (target download dir), add COUCHPOTATO_MOVIES_DIR_* vars for additional dirs
      - COUCHPOTATO_MOVIES_MAIN_DIR=/storage/_hd1/Films
      - COUCHPOTATO_MOVIES_DIR_2=/storage/_hd1/Enfants/Films
      - COUCHPOTATO_MOVIES_DIR_3=/storage/Films
      # _______________________________________________________________
      # nginx config (credentials stored in .env file)
      - NGINX_USERNAME=${NGINX_USERNAME}
      - NGINX_PASSWORD=${NGINX_PASSWORD}
      # _______________________________________________________________
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Storage dirs
      - /shares/P2P/tools:/config
    
    restart: "no"
