version: "3.3"

services:
  
  # ==========================================================================
  # Configurator service for docker torrent factory
  # => initialize or update config files for other services (JOAL, Kodi MariaDB, Medusa, nginx)
  # => must be executed on-demand before starting other services
  configurator:
    image: ahuh/dtf-configurator:latest
    container_name: configurator

    environment:
      # _______________________________________________________________
      # Medusa config
      # • Use HTTP proxy for torrent search (true / false)
      - MEDUSA_USE_HTTP_PROXY=false
      # • Torrent dirs
      - MEDUSA_TORRENT_DOWNLOAD_DIR=/storage/complete/medusa
      - MEDUSA_TORRENT_SEED_DIR=/storage/complete/seed
      # • Storage dirs for TV shows : MEDUSA_TVSHOWS_MAIN_DIR required, add MEDUSA_TVSHOWS_DIR_* vars for additional dirs
      - MEDUSA_TVSHOWS_MAIN_DIR=/storage/Series
      - MEDUSA_TVSHOWS_DIR_2=/storage/Enfants/Series
      # _______________________________________________________________
      # nginx config (credentials stored in .env file)
      - NGINX_USERNAME=${NGINX_USERNAME}
      - NGINX_PASSWORD=${NGINX_PASSWORD}
      # _______________________________________________________________
      # User from docker host to impersonate in container (configured in .env file)
      - PUID=${USER_PUID}
      - PGID=${USER_PGID}
    
    volumes:
      # Sync time with docker host
      - /etc/localtime:/etc/localtime:ro
      # Storage dirs
      - /share/Download/tools:/config
    
    restart: "no"
